export const SET_APP_LOCKED = 'SET_APP_LOCKED';
export const SET_POOL_DATA = 'SET_POOL_DATA';
export const SET_SELECTED_POOL_ID = 'SET_SELECTED_POOL_ID';
export const FETCH_POOLS = 'FETCH_POOLS';
export const FETCH_POOLS_FAILED = 'FETCH_POOLS_FAILED';
export const LOAD_CHANGE_ACTION = 'LOAD_CHANGE_ACTION';
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export const SET_BUNDLED_ADDRESS = 'SET_BUNDLED_ADDRESS';
export const SET_ADDRESSES = 'SET_ADDRESSES';
export const FETCH_SNAPS_FAILED = 'FETCH_SNAPS_FAILED';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_NO_POOLS_FOUND = 'SET_NO_POOLS_FOUND';
export const FETCH_SNAPS_SUCCESS = 'FETCH_SNAPS_SUCCESS';
export const NO_POOLS_FOUND = 'NO_POOLS_FOUND';
export const FETCH_SNAPS_INIT = 'FETCH_SNAPS_INIT';
export const SET_THEME = 'SET_THEME';
export const FETCH_DAILY_SUCCESS = 'FETCH_DAILY_SUCCESS';
export const FETCH_DAILY_INIT = 'FETCH_DAILY_INIT';
export const FETCH_DAILY_FAILED = 'FETCH_DAILY_FAILED';

// Modals
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// Window resize hook
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';

// Simulator
export const FETCH_IMPORTED_POOL = 'FETCH_IMPORTED_POOL';
export const SET_FETCH_POOL_SNAP_LOADING = 'SET_FETCH_POOL_SNAP_LOADING';
export const FETCH_POOL_SNAP_INIT = 'FETCH_POOL_SNAP_INIT';
export const FETCH_POOL_SNAP_SUCCESS = 'FETCH_POOL_SNAP_SUCCESS';
export const FETCH_POOL_SNAP_FAILED = 'FETCH_POOL_SNAP_FAILED';
export const SET_NEW_SIMULATION_POOL_DATA = 'SET_NEW_SIMULATION_POOL_DATA';
export const CLEAR_POOL_SNAP_DATA = 'CLEAR_POOL_SNAP_DATA';
export const SET_SIMULATION_MODE = 'SET_SIMULATION_MODE';
export const SET_TOKEN_COEFFICIENTS = 'SET_TOKEN_COEFFICIENTS';
export const SET_ETH_COEFFICIENT = 'SET_ETH_COEFFICIENT';
export const SET_YIELD_COEFFICIENT = 'SET_YIELD_COEFFICIENT';
export const SET_DEFAULT_SLIDER_TOKEN_COEFFICIENTS = 'SET_DEFAULT_SLIDER_TOKEN_COEFFICIENTS';
export const SET_DEFAULT_SLIDER_ETH_COEFFICIENTS = 'SET_DEFAULT_SLIDER_ETH_COEFFICIENTS';
export const RESET_SIMULATION_COEFFICIENTS = 'RESET_SIMULATION_COEFFICIENTS';
