export const SET_ALL_POOLS = 'SET_ALL_POOLS';
export const SET_SELECTED_POOL_ID = 'SET_SELECTED_POOL_ID';
export const SET_EXCHANGE_TO_POOLS_MAPPING = 'SET_EXCHANGE_TO_POOLS_MAPPING';
export const FETCH_POOLS = 'FETCH_POOLS';
export const FETCH_POOLS_FAILED = 'FETCH_POOLS_FAILED';
export const LOAD_CHANGE_ACTION = 'LOAD_CHANGE_ACTION';
