/* eslint-disable global-require */
export const TOKENS: any = {
    aave: require('../../../data/images/tokens/aave.svg'),
    bal: require('../../../data/images/tokens/bal.svg'),
    comp: require('../../../data/images/tokens/comp.svg'),
    dai: require('../../../data/images/tokens/dai.svg'),
    eth: require('../../../data/images/tokens/weth.svg'),
    keep: require('../../../data/images/tokens/keep.svg'),
    lend: require('../../../data/images/tokens/lend.svg'),
    link: require('../../../data/images/tokens/link.svg'),
    mkr: require('../../../data/images/tokens/mkr.svg'),
    musd: require('../../../data/images/tokens/musd.svg'),
    uni: require('../../../data/images/tokens/uni.svg'),
    usdc: require('../../../data/images/tokens/usdc.svg'),
    usdt: require('../../../data/images/tokens/usdt.svg'),
    wbtc: require('../../../data/images/tokens/wbtc.svg'),
    yam: require('../../../data/images/tokens/yam.svg'),
    yfi: require('../../../data/images/tokens/yfi.svg'),
    snx: require('../../../data/images/tokens/snx.svg'),
    weth: require('../../../data/images/tokens/weth.svg'),
    sushi: require('../../../data/images/tokens/sushi.svg'),
    yfv: require('../../../data/images/tokens/yfv.svg'),
    renbtc: require('../../../data/images/tokens/renbtc.svg'),
    dpi: require('../../../data/images/tokens/dpi.svg'),
    farm: require('../../../data/images/tokens/farm.svg'),
    fil: require('../../../data/images/tokens/fil.svg'),
    grt: require('../../../data/images/tokens/grt.svg'),
    lrc: require('../../../data/images/tokens/lrc.svg'),
    omg: require('../../../data/images/tokens/omg.svg'),
    pickle: require('../../../data/images/tokens/pickle.svg'),
    zrx: require('../../../data/images/tokens/zrx.svg'),

    // unknown token
    unknown: require('../../../data/images/tokens/unknown.svg'),
    // exchanges
    uniswap: require('../../../data/images/exchanges/uniswap.svg'),
    uni_v1: require('../../../data/images/exchanges/uniswap.svg'),
    uni_v2: require('../../../data/images/exchanges/uniswap.svg'),
    balancer: require('../../../data/images/exchanges/balancer.svg'),
};
