/* eslint-disable global-require */
export const TOKENS = {
    aave: require('../../../data/images/tokens/aave.svg'),
    bal: require('../../../data/images/tokens/bal.svg'),
    comp: require('../../../data/images/tokens/comp.svg'),
    dai: require('../../../data/images/tokens/dai.svg'),
    eth: require('../../../data/images/tokens/weth.svg'),
    keep: require('../../../data/images/tokens/keep.svg'),
    lend: require('../../../data/images/tokens/lend.svg'),
    link: require('../../../data/images/tokens/link.svg'),
    mkr: require('../../../data/images/tokens/mkr.svg'),
    musd: require('../../../data/images/tokens/musd.svg'),
    uni: require('../../../data/images/tokens/uni.svg'),
    usdc: require('../../../data/images/tokens/usdc.svg'),
    usdt: require('../../../data/images/tokens/usdt.svg'),
    wbtc: require('../../../data/images/tokens/wbtc.svg'),
    yam: require('../../../data/images/tokens/yam.svg'),
    yfi: require('../../../data/images/tokens/yfi.svg'),
    snx: require('../../../data/images/tokens/snx.svg'),
    weth: require('../../../data/images/tokens/weth.svg'),
    sushi: require('../../../data/images/tokens/sushi.svg'),
    yfv: require('../../../data/images/tokens/yfv.svg'),
    renbtc: require('../../../data/images/tokens/renbtc.svg'),
    dpi: require('../../../data/images/tokens/dpi.svg'),
    farm: require('../../../data/images/tokens/farm.svg'),
    fil: require('../../../data/images/tokens/fil.svg'),
    grt: require('../../../data/images/tokens/grt.svg'),
    lrc: require('../../../data/images/tokens/lrc.svg'),
    omg: require('../../../data/images/tokens/omg.svg'),
    pickle: require('../../../data/images/tokens/pickle.svg'),
    zrx: require('../../../data/images/tokens/zrx.svg'),
    knc: require('../../../data/images/tokens/knc.svg'),
    ren: require('../../../data/images/tokens/ren.svg'),
    '1inch': require('../../../data/images/tokens/1inch.svg'),
    meme: require('../../../data/images/tokens/meme.svg'),
    wusd: require('../../../data/images/tokens/wusd.svg'),
    alpha: require('../../../data/images/tokens/alpha.svg'),
    vision: require('../../../data/images/tokens/vision.svg'),
    tbtc: require('../../../data/images/tokens/tbtc.svg'),
    crv: require('../../../data/images/tokens/crv.svg'),
    cover: require('../../../data/images/tokens/cover.svg'),

    // unknown token
    unknown: require('../../../data/images/tokens/unknown.svg'),
    // exchanges
    uniswap: require('../../../data/images/exchanges/uniswap.svg'),
    uniswapdark: require('../../../data/images/exchanges/uniswap-dark.svg'),
    uni_v1: require('../../../data/images/exchanges/uniswap.svg'),
    uni_v2: require('../../../data/images/exchanges/uniswap.svg'),
    uni_v2dark: require('../../../data/images/exchanges/uniswap-dark.svg'),
    balancer: require('../../../data/images/exchanges/balancer.svg'),
    balancerdark: require('../../../data/images/exchanges/balancer-dark.svg'),
    sushidark: require('../../../data/images/exchanges/sushi-dark.svg'),
    materia: require('../../../data/images/exchanges/materia.svg'),
    materiadark: require('../../../data/images/exchanges/materia_dark.svg'),
};
